version: "3.7"
services:
  node:
    image: node_f
    container_name: remo_f
    entrypoint: sh
    ports:
      - 3004:3004
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /home/${project?}
    working_dir: /home/${project?}